// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu4gThsxz6Ya5QNpCx691c0fdLZ5LtSUY',
    appId: '1:360956409926:web:e721eb41ab53ffd7d37247',
    messagingSenderId: '360956409926',
    projectId: 'flutter-app-notification-9424c',
    authDomain: 'flutter-app-notification-9424c.firebaseapp.com',
    storageBucket: 'flutter-app-notification-9424c.appspot.com',
    measurementId: 'G-E1TMW1KGDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK4A43fJvTgxdxOI-JgE09L3k9-5oO6uQ',
    appId: '1:360956409926:android:e4a15d372e37e6dfd37247',
    messagingSenderId: '360956409926',
    projectId: 'flutter-app-notification-9424c',
    storageBucket: 'flutter-app-notification-9424c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcRpMd1tMQqQgUa3qBchYXSdc1PoOaXyE',
    appId: '1:360956409926:ios:9e02dc047b9dac00d37247',
    messagingSenderId: '360956409926',
    projectId: 'flutter-app-notification-9424c',
    storageBucket: 'flutter-app-notification-9424c.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcRpMd1tMQqQgUa3qBchYXSdc1PoOaXyE',
    appId: '1:360956409926:ios:50db29797a020f0bd37247',
    messagingSenderId: '360956409926',
    projectId: 'flutter-app-notification-9424c',
    storageBucket: 'flutter-app-notification-9424c.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseNotifications.RunnerTests',
  );
}
